image:
# - Visual Studio 2015
- Visual Studio 2019

build:
  parallel: true

platform:
  - x64

configuration:
  - Release

environment:
  CONDA_DIR: C:\Miniconda3-x64

matrix:
  fast_finish: true

init:
  - set PATH=%CONDA_DIR%;%CONDA_DIR%\Scripts;%CONDA_DIR%\Library\bin;%PATH%

install:
  - call ci\appveyor\install.bat

build_script:
  - call ci\appveyor\build.bat

test_script:
  - conda list
  - call ci\appveyor\test.bat
