# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master
- releases/*

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-20.04'

  steps:
  - task: Bash@3
    inputs:
      filePath: 'ci/pipelines/install.sh'

- job: macOS
  pool:
    vmImage: 'macOS-11'

  steps:
  - task: Bash@3
    inputs:
      filePath: 'ci/pipelines/install/install-osx.sh'

# - job: win64
#   pool:
#     vmImage: 'windows-2019'
#   strategy:
#     matrix:
#       Python37:
#         python.version: '3.7'

#   steps:
#   - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
#     displayName: Add conda to PATH

#   - script: |
#       conda config --system --set always_yes yes --set changeps1 no
#       conda config --system --append channels conda-forge
#       conda install -n base conda-devenv
#       conda update -q conda
#       conda info -a
#       conda devenv
#       call activate thermofun
#     displayName: Create Anaconda environment

#   - task: BatchScript@1
#     inputs:
#       filename: 'ci/pipelines/install.bat'

#   - script: |
#      call activate thermofun
#      conda list
#      call python -c "import thermofun"
#     displayName: Test

- job: win64_VS
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: |
      conda config --system --set always_yes yes --set changeps1 no
      conda config --system --append channels conda-forge
      conda install -n base conda-devenv
      conda update -q conda
      conda info -a
      conda devenv
      call activate thermofun
    displayName: Create Anaconda environment

  - task: BatchScript@1
    inputs:
      filename: 'ci/pipelines/installVS.bat'

  - script: |
     call activate thermofun
     conda list
     call python -c "import thermofun"
    displayName: Test
