// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 ThermoFun contributors

// Generated by python/tools/generate_enums.py from ThermoFun/GlobalVariables.h: do not edit.
// Python bindings of the enumerations used by the setters and getters of Substance and Reaction and by the models.

#if _MSC_VER >= 1929
#include <corecrt.h>
#endif

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
namespace py = pybind11;

#include <ThermoFun/GlobalVariables.h>

namespace ThermoFun {

void exportGlobalVariables(py::module& m)
{
    {
        py::enum_<MethodGenEoS_Thrift::type> e(m, "MethodGenEoS_Thrift");
        e.value("CTPM_CON", MethodGenEoS_Thrift::CTPM_CON);
        e.value("CTPM_CPT", MethodGenEoS_Thrift::CTPM_CPT);
        e.value("CTPM_HKF", MethodGenEoS_Thrift::CTPM_HKF);
        e.value("CTPM_REA", MethodGenEoS_Thrift::CTPM_REA);
        e.value("CTPM_EOS", MethodGenEoS_Thrift::CTPM_EOS);
        e.value("CTPM_ISO", MethodGenEoS_Thrift::CTPM_ISO);
        e.value("CTPM_SOR", MethodGenEoS_Thrift::CTPM_SOR);
        e.value("CEM_OFF", MethodGenEoS_Thrift::CEM_OFF);
        e.value("CEM_GAS", MethodGenEoS_Thrift::CEM_GAS);
        e.value("CEM_H2O", MethodGenEoS_Thrift::CEM_H2O);
        e.value("CEM_CO2", MethodGenEoS_Thrift::CEM_CO2);
        e.value("CEM_CH4", MethodGenEoS_Thrift::CEM_CH4);
        e.value("CEM_N2", MethodGenEoS_Thrift::CEM_N2);
        e.value("CEM_H2", MethodGenEoS_Thrift::CEM_H2);
        e.value("CEM_O2", MethodGenEoS_Thrift::CEM_O2);
        e.value("CEM_AR", MethodGenEoS_Thrift::CEM_AR);
        e.value("CEM_PO", MethodGenEoS_Thrift::CEM_PO);
        e.value("CEM_NP", MethodGenEoS_Thrift::CEM_NP);
        e.value("CTPM_WJNR", MethodGenEoS_Thrift::CTPM_WJNR);
        e.value("CTPM_WJNG", MethodGenEoS_Thrift::CTPM_WJNG);
        e.value("CTPM_HKFR", MethodGenEoS_Thrift::CTPM_HKFR);
        e.value("CTPM_WSV14", MethodGenEoS_Thrift::CTPM_WSV14);
        e.value("CTPM_WF97", MethodGenEoS_Thrift::CTPM_WF97);
        e.value("CTPM_HP98", MethodGenEoS_Thrift::CTPM_HP98);
        e.value("CTPM_AN91", MethodGenEoS_Thrift::CTPM_AN91);
    }
    {
        py::enum_<MethodCorrT_Thrift::type> e(m, "MethodCorrT_Thrift");
        e.value("CTM_CST", MethodCorrT_Thrift::CTM_CST);
        e.value("CTM_CHP", MethodCorrT_Thrift::CTM_CHP);
        e.value("CTM_BER", MethodCorrT_Thrift::CTM_BER);
        e.value("CTM_FEI", MethodCorrT_Thrift::CTM_FEI);
        e.value("CTM_LGX", MethodCorrT_Thrift::CTM_LGX);
        e.value("CTM_HKF", MethodCorrT_Thrift::CTM_HKF);
        e.value("CTM_WAT", MethodCorrT_Thrift::CTM_WAT);
        e.value("CTM_WAS", MethodCorrT_Thrift::CTM_WAS);
        e.value("CTM_LGK", MethodCorrT_Thrift::CTM_LGK);
        e.value("CTM_EK0", MethodCorrT_Thrift::CTM_EK0);
        e.value("CTM_EK1", MethodCorrT_Thrift::CTM_EK1);
        e.value("CTM_EK2", MethodCorrT_Thrift::CTM_EK2);
        e.value("CTM_EK3", MethodCorrT_Thrift::CTM_EK3);
        e.value("CTM_IKZ", MethodCorrT_Thrift::CTM_IKZ);
        e.value("CTM_DKR", MethodCorrT_Thrift::CTM_DKR);
        e.value("CTM_PPE", MethodCorrT_Thrift::CTM_PPE);
        e.value("CTM_MRB", MethodCorrT_Thrift::CTM_MRB);
        e.value("CTM_CPG", MethodCorrT_Thrift::CTM_CPG);
        e.value("CTM_IFG", MethodCorrT_Thrift::CTM_IFG);
        e.value("CTM_KAS", MethodCorrT_Thrift::CTM_KAS);
        e.value("CTM_DAS", MethodCorrT_Thrift::CTM_DAS);
        e.value("CTM_WAR", MethodCorrT_Thrift::CTM_WAR);
        e.value("CTM_WWP", MethodCorrT_Thrift::CTM_WWP);
        e.value("CTM_WZD", MethodCorrT_Thrift::CTM_WZD);
        e.value("CTM_DMD", MethodCorrT_Thrift::CTM_DMD);
    }
    {
        py::enum_<MethodCorrP_Thrift::type> e(m, "MethodCorrP_Thrift");
        e.value("CPM_OFF", MethodCorrP_Thrift::CPM_OFF);
        e.value("CPM_NUL", MethodCorrP_Thrift::CPM_NUL);
        e.value("CPM_ONE", MethodCorrP_Thrift::CPM_ONE);
        e.value("CPM_TWO", MethodCorrP_Thrift::CPM_TWO);
        e.value("CPM_TRI", MethodCorrP_Thrift::CPM_TRI);
        e.value("CPM_CON", MethodCorrP_Thrift::CPM_CON);
        e.value("CPM_VKE", MethodCorrP_Thrift::CPM_VKE);
        e.value("CPM_VBE", MethodCorrP_Thrift::CPM_VBE);
        e.value("CPM_VBM", MethodCorrP_Thrift::CPM_VBM);
        e.value("CPM_CEH", MethodCorrP_Thrift::CPM_CEH);
        e.value("CPM_VTA", MethodCorrP_Thrift::CPM_VTA);
        e.value("CPM_GAS", MethodCorrP_Thrift::CPM_GAS);
        e.value("CPM_PRSV", MethodCorrP_Thrift::CPM_PRSV);
        e.value("CPM_EMP", MethodCorrP_Thrift::CPM_EMP);
        e.value("CPM_SRK", MethodCorrP_Thrift::CPM_SRK);
        e.value("CPM_STP", MethodCorrP_Thrift::CPM_STP);
        e.value("CPM_PR78", MethodCorrP_Thrift::CPM_PR78);
        e.value("CPM_CORK", MethodCorrP_Thrift::CPM_CORK);
        e.value("CPM_REFL", MethodCorrP_Thrift::CPM_REFL);
        e.value("CPM_HKF", MethodCorrP_Thrift::CPM_HKF);
        e.value("CPM_AKI", MethodCorrP_Thrift::CPM_AKI);
        e.value("CPM_PCR", MethodCorrP_Thrift::CPM_PCR);
        e.value("CPM_INK", MethodCorrP_Thrift::CPM_INK);
    }
    {
        py::enum_<ConcentrationScales::type> e(m, "ConcentrationScales");
        e.value("C_MOLFRACTION", ConcentrationScales::C_MOLFRACTION);
        e.value("C_PARTIALPRESSURE", ConcentrationScales::C_PARTIALPRESSURE);
        e.value("C_MOLALITY", ConcentrationScales::C_MOLALITY);
        e.value("C_MOLARITY", ConcentrationScales::C_MOLARITY);
        e.value("C_MASSFRACTION", ConcentrationScales::C_MASSFRACTION);
        e.value("C_SURFACEFRACTION", ConcentrationScales::C_SURFACEFRACTION);
        e.value("C_SURFACEDENSITY", ConcentrationScales::C_SURFACEDENSITY);
        e.value("C_SITEFRACTION", ConcentrationScales::C_SITEFRACTION);
        e.value("C_OTHER", ConcentrationScales::C_OTHER);
    }
    {
        py::enum_<SubstanceClass::type> e(m, "SubstanceClass");
        e.value("COMPONENT", SubstanceClass::COMPONENT);
        e.value("GASFLUID", SubstanceClass::GASFLUID);
        e.value("AQSOLUTE", SubstanceClass::AQSOLUTE);
        e.value("AQSOLVENT", SubstanceClass::AQSOLVENT);
        e.value("SURFSPECIES", SubstanceClass::SURFSPECIES);
        e.value("SITEMOIETY", SubstanceClass::SITEMOIETY);
        e.value("OTHER_SC", SubstanceClass::OTHER_SC);
    }
    {
        py::enum_<AggregateState::type> e(m, "AggregateState");
        e.value("GAS", AggregateState::GAS);
        e.value("LIQUID", AggregateState::LIQUID);
        e.value("GLASS", AggregateState::GLASS);
        e.value("CRYSTAL", AggregateState::CRYSTAL);
        e.value("AQUEOUS", AggregateState::AQUEOUS);
        e.value("SURFACE", AggregateState::SURFACE);
        e.value("IONEX", AggregateState::IONEX);
        e.value("PLASMA", AggregateState::PLASMA);
        e.value("SOLID", AggregateState::SOLID);
        e.value("CONDENSED", AggregateState::CONDENSED);
        e.value("FLUID", AggregateState::FLUID);
        e.value("LIQUIDCRYSTAL", AggregateState::LIQUIDCRYSTAL);
        e.value("AMORPHOUSSOLID", AggregateState::AMORPHOUSSOLID);
        e.value("MONOMERIC", AggregateState::MONOMERIC);
        e.value("POLYMERIC", AggregateState::POLYMERIC);
        e.value("SOLIDSOLUTION", AggregateState::SOLIDSOLUTION);
        e.value("OTHER", AggregateState::OTHER);
    }
    {
        py::enum_<ReactionComponentType::type> e(m, "ReactionComponentType");
        e.value("REACTANT", ReactionComponentType::REACTANT);
        e.value("PRODUCT", ReactionComponentType::PRODUCT);
        e.value("CATALYST", ReactionComponentType::CATALYST);
        e.value("OTHER_RC", ReactionComponentType::OTHER_RC);
    }
    {
        py::enum_<SubstanceThermoCalculationType::type> e(m, "SubstanceThermoCalculationType");
        e.value("DCOMP", SubstanceThermoCalculationType::DCOMP);
        e.value("REACDC", SubstanceThermoCalculationType::REACDC);
    }
    {
        py::enum_<RectionThermoCalculationType::type> e(m, "RectionThermoCalculationType");
        e.value("REACTION", RectionThermoCalculationType::REACTION);
        e.value("REACTANTS", RectionThermoCalculationType::REACTANTS);
    }
    {
        py::enum_<SubstanceTPMethodType> e(m, "SubstanceTPMethodType");
        e.value("cp_ft_equation", SubstanceTPMethodType::cp_ft_equation);
        e.value("cp_ft_equation_saxena86", SubstanceTPMethodType::cp_ft_equation_saxena86);
        e.value("solute_hkf88_gems", SubstanceTPMethodType::solute_hkf88_gems);
        e.value("solute_hkf88_reaktoro", SubstanceTPMethodType::solute_hkf88_reaktoro);
        e.value("solute_aknifiev_diamond03", SubstanceTPMethodType::solute_aknifiev_diamond03);
        e.value("landau_holland_powell98", SubstanceTPMethodType::landau_holland_powell98);
        e.value("landau_berman88", SubstanceTPMethodType::landau_berman88);
        e.value("general_equation_of_state", SubstanceTPMethodType::general_equation_of_state);
        e.value("fug_critical_param", SubstanceTPMethodType::fug_critical_param);
        e.value("fluid_prsv", SubstanceTPMethodType::fluid_prsv);
        e.value("fluid_churakov_gottschalk", SubstanceTPMethodType::fluid_churakov_gottschalk);
        e.value("fluid_soave_redlich_kwong", SubstanceTPMethodType::fluid_soave_redlich_kwong);
        e.value("fluid_sterner_pitzer", SubstanceTPMethodType::fluid_sterner_pitzer);
        e.value("fluid_peng_robinson78", SubstanceTPMethodType::fluid_peng_robinson78);
        e.value("fluid_comp_redlich_kwong_hp91", SubstanceTPMethodType::fluid_comp_redlich_kwong_hp91);
        e.value("fluid_generic", SubstanceTPMethodType::fluid_generic);
        e.value("fluid_H2O", SubstanceTPMethodType::fluid_H2O);
        e.value("fluid_CO2", SubstanceTPMethodType::fluid_CO2);
        e.value("fluid_CH4", SubstanceTPMethodType::fluid_CH4);
        e.value("fluid_N2", SubstanceTPMethodType::fluid_N2);
        e.value("fluid_H2", SubstanceTPMethodType::fluid_H2);
        e.value("fluid_O2", SubstanceTPMethodType::fluid_O2);
        e.value("fluid_Ar", SubstanceTPMethodType::fluid_Ar);
        e.value("fluid_polar", SubstanceTPMethodType::fluid_polar);
        e.value("fluid_nonpolar", SubstanceTPMethodType::fluid_nonpolar);
        e.value("water_diel_jnort91_reaktoro", SubstanceTPMethodType::water_diel_jnort91_reaktoro);
        e.value("water_diel_jnort91_gems", SubstanceTPMethodType::water_diel_jnort91_gems);
        e.value("water_diel_sverj14", SubstanceTPMethodType::water_diel_sverj14);
        e.value("water_diel_fern97", SubstanceTPMethodType::water_diel_fern97);
        e.value("water_eos_hgk84_lvs83_gems", SubstanceTPMethodType::water_eos_hgk84_lvs83_gems);
        e.value("water_eos_iapws95_gems", SubstanceTPMethodType::water_eos_iapws95_gems);
        e.value("water_eos_hgk84_reaktoro", SubstanceTPMethodType::water_eos_hgk84_reaktoro);
        e.value("water_eos_iapws95_reaktoro", SubstanceTPMethodType::water_eos_iapws95_reaktoro);
        e.value("water_pvt_zhang_duan05", SubstanceTPMethodType::water_pvt_zhang_duan05);
        e.value("mv_constant", SubstanceTPMethodType::mv_constant);
        e.value("mv_equation_dorogokupets88", SubstanceTPMethodType::mv_equation_dorogokupets88);
        e.value("mv_equation_berman88", SubstanceTPMethodType::mv_equation_berman88);
        e.value("mv_eos_birch_murnaghan_gott97", SubstanceTPMethodType::mv_eos_birch_murnaghan_gott97);
        e.value("mv_eos_murnaghan_hp98", SubstanceTPMethodType::mv_eos_murnaghan_hp98);
        e.value("mv_eos_tait_hp11", SubstanceTPMethodType::mv_eos_tait_hp11);
        e.value("mv_pvnrt", SubstanceTPMethodType::mv_pvnrt);
        e.value("solute_holland_powell98", SubstanceTPMethodType::solute_holland_powell98);
        e.value("solute_anderson91", SubstanceTPMethodType::solute_anderson91);
        e.value("standard_entropy_cp_integration", SubstanceTPMethodType::standard_entropy_cp_integration);
    }
    {
        py::enum_<ReactionTPMethodType> e(m, "ReactionTPMethodType");
        e.value("logk_fpt_function", ReactionTPMethodType::logk_fpt_function);
        e.value("adsor_ion_exchange", ReactionTPMethodType::adsor_ion_exchange);
        e.value("iso_compounds_grichuk88", ReactionTPMethodType::iso_compounds_grichuk88);
        e.value("logk_nordstrom_munoz88", ReactionTPMethodType::logk_nordstrom_munoz88);
        e.value("logk_1_term_extrap0", ReactionTPMethodType::logk_1_term_extrap0);
        e.value("logk_1_term_extrap1", ReactionTPMethodType::logk_1_term_extrap1);
        e.value("logk_2_term_extrap", ReactionTPMethodType::logk_2_term_extrap);
        e.value("logk_3_term_extrap", ReactionTPMethodType::logk_3_term_extrap);
        e.value("logk_lagrange_interp", ReactionTPMethodType::logk_lagrange_interp);
        e.value("logk_marshall_frank78", ReactionTPMethodType::logk_marshall_frank78);
        e.value("solute_eos_ryzhenko_gems", ReactionTPMethodType::solute_eos_ryzhenko_gems);
        e.value("dr_heat_capacity_ft", ReactionTPMethodType::dr_heat_capacity_ft);
        e.value("dr_volume_fpt", ReactionTPMethodType::dr_volume_fpt);
        e.value("dr_volume_constant", ReactionTPMethodType::dr_volume_constant);
        e.value("logk_dolejs_manning10", ReactionTPMethodType::logk_dolejs_manning10);
    }

    // the names of the methods by code, the constants and the reference values of the properties of water
    m.attr("enum_method_substance") = py::cast(enum_method_substance);
    m.attr("enum_method_reaction") = py::cast(enum_method_reaction);
    m.attr("R_CONSTANT") = R_CONSTANT;
    m.attr("NA_CONSTANT") = NA_CONSTANT;
    m.attr("F_CONSTANT") = F_CONSTANT;
    m.attr("e_CONSTANT") = e_CONSTANT;
    m.attr("k_CONSTANT") = k_CONSTANT;
    m.attr("cal_to_J") = cal_to_J;
    m.attr("C_to_K") = C_to_K;
    m.attr("lg_to_ln") = lg_to_ln;
    m.attr("ln_to_lg") = ln_to_lg;
    m.attr("H2O_mol_to_kg") = H2O_mol_to_kg;
    m.attr("bar_to_Pa") = bar_to_Pa;
    m.attr("H2OMolarMass") = H2OMolarMass;
}

} // namespace ThermoFun
