#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
# Copyright (C) 2026 ThermoFun contributors

"""Generate python/src/thermofun/pyGlobalVariables.cpp (the pybind11 bindings of the enumerations of
ThermoFun/GlobalVariables.h). Run from the root of the repository after the enumerations changed:
    python3 python/tools/generate_enums.py
"""
import re
import os

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
header = open(os.path.join(root, "ThermoFun/GlobalVariables.h")).read()


def enumerators(body):
    names = []
    for line in body.splitlines():
        line = line.split("//")[0].strip()
        if not line:
            continue
        m = re.match(r"([A-Za-z_]\w*)\s*(=\s*[^,]+)?,?$", line)
        if m:
            names.append(m.group(1))
    return names


# typedef struct { enum type { ... }; } Name;
scoped = []
for m in re.finditer(r"typedef\s+struct\s*\{\s*enum\s+type\s*\{(.*?)\};\s*\}\s*(\w+)\s*;", header, re.S):
    scoped.append((m.group(2), enumerators(m.group(1))))
# enum Name { ... };
plain = []
for m in re.finditer(r"^enum\s+(\w+)\s*\{(.*?)\};", header, re.S | re.M):
    plain.append((m.group(1), enumerators(m.group(2))))

out = []
out.append("""// Generated by python/tools/generate_enums.py from ThermoFun/GlobalVariables.h: do not edit.
// Python bindings of the enumerations used by the setters and getters of Substance and Reaction and by the models.

#if _MSC_VER >= 1929
#include <corecrt.h>
#endif

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
namespace py = pybind11;

#include <ThermoFun/GlobalVariables.h>

namespace ThermoFun {

void exportGlobalVariables(py::module& m)
{""")
for name, vals in scoped:
    out.append('    {\n        py::enum_<%s::type> e(m, "%s");' % (name, name))
    for v in vals:
        out.append('        e.value("%s", %s::%s);' % (v, name, v))
    out.append("    }")
for name, vals in plain:
    out.append('    {\n        py::enum_<%s> e(m, "%s");' % (name, name))
    for v in vals:
        out.append('        e.value("%s", %s::%s);' % (v, name, v))
    out.append("    }")
out.append('''
    // the names of the methods by code, the constants and the reference values of the properties of water
    m.attr("enum_method_substance") = py::cast(enum_method_substance);
    m.attr("enum_method_reaction") = py::cast(enum_method_reaction);
    m.attr("R_CONSTANT") = R_CONSTANT;
    m.attr("NA_CONSTANT") = NA_CONSTANT;
    m.attr("F_CONSTANT") = F_CONSTANT;
    m.attr("e_CONSTANT") = e_CONSTANT;
    m.attr("k_CONSTANT") = k_CONSTANT;
    m.attr("cal_to_J") = cal_to_J;
    m.attr("C_to_K") = C_to_K;
    m.attr("lg_to_ln") = lg_to_ln;
    m.attr("ln_to_lg") = ln_to_lg;
    m.attr("H2O_mol_to_kg") = H2O_mol_to_kg;
    m.attr("bar_to_Pa") = bar_to_Pa;
    m.attr("H2OMolarMass") = H2OMolarMass;
}

} // namespace ThermoFun''')
path = os.path.join(root, "python/src/thermofun/pyGlobalVariables.cpp")
open(path, "w").write("\n".join(out) + "\n")
print("scoped:", [n for n, _ in scoped])
print("plain:", [n for n, _ in plain])
